parameters:
  - name: skip_code_scan
    displayName: Skip Code Scan
    type: boolean
    default: true

trigger:
  branches:
    include:
      - refs/tags/vailley-mono-t-avatar

pr: none

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/tags/vailley-mono-t-avatar') }}:
      - group: vailley-mono-t-avatar

pool:
  name: $(agent_pool)

stages:
  - template: ../templates/ci.yml
    parameters:
      skip_code_scan: ${{ parameters.skip_code_scan }}
      service_connection: $(sonar_service_connection)
      organization: $(sonar_organization)
      project_key: $(sonar_project_key)
      project_name: $(sonar_project_name)
      sources: $(sonar_sources)
  - stage: cd
    displayName: CD
    dependsOn: [ci]
    jobs:
      - job: build_deploy
        displayName: Build & Deploy
        steps:
          - checkout: self
            displayName: Checkout source
            clean: true
          - task: Docker@2
            displayName: Build image
            inputs:
              containerRegistry: '$(service_connection_acr)'
              repository: '$(container_repository)'
              command: 'build'
              Dockerfile: './packages/t-avatar/Dockerfile'
              buildContext: '.'
              arguments: ''
          - task: Docker@2
            displayName: Push image
            inputs:
              command: push
              containerRegistry: $(service_connection_acr)
              repository: $(container_repository)
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '20.x'
              checkLatest: true
          - task: AzureCLI@2
            displayName: Restart t-avatar
            inputs:
              azureSubscription: '$(service_connection_arm)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az vm run-command invoke -g $(resource_group) -n $(vm_name) --command-id RunShellScript --scripts "sudo /bin/sh /app/vailley-mono/t-avatar/restart-t-avatar-container.sh $(docker_service_name) $(container_registry) $(container_repository) $(Build.BuildId)"
